name: Docker-ghcr

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "dev", "staging", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}


jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: ${{ github.head_ref || github.ref_name }}
    steps:
      - name: Set .npmrc Content Environment Variable
        run: |
          echo "NPMRC_CONTENT=//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "@usepa:registry=https://npm.pkg.github.com/" >> $GITHUB_ENV
        shell: bash
        
      - name: Checkout code
        uses: USEPA/ccte-docker-build@main
        with:
          username: USEPA
          password: ${{ secrets.GITHUB_TOKEN }}
          image_name: ${{ github.repository }}-${{ github.head_ref || github.ref_name }}
          env_text: ${{vars.ENV_TEXT}}
          npmrc_content: ${{ env.NPMRC_CONTENT }}
